### ISSUE TITLE
product.upsertMany expects at least two products

### ISSUE THREAD

**Issue by LarsBuur** [ajmnz/akeneo-node#6]
Thank you for a really good start on a typed akeneo api.

If I try to upsert just one product using product.upsertMany then collectionToArray (AkeneoCore.ts 139) expect the response to have multiple lines which fails with a ``` TypeError: coll.split is not a function```

I am not (yet) fully into all aspects of the code to create a proper fix.

**Comment by ajmnz** [comment]
Also ran into this issue and _I think_ I fixed this in the latest beta version (available on npm). Either way, I'll release

**Comment by ajmnz** [comment]
Also ran into this issue and _I think_ I fixed this in the latest beta version (available on npm). Either way, I'll release 0.0.5 today with a proper fix.

**Comment by ajmnz** [comment]
`0.0.5` now available on npm. Please give it a try and let me know if this issue is fixed.
